name: Release
on:
  push:
    branches:
      - master
      - main
      - beta
      - alpha
      - ?.[xX]
      - ?.?.[xX]

permissions:
  contents: read # for checkout

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/_release.yml
    with:
      config: "./release.config.js"